version: '3'

services:
  app:
    container_name: 'ihub'
    restart: always
    build:
      context: .
      dockerfile: app_dockerfile
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
     - .:/ihub
    ports:
     - "8000:8000"
