# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-17 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sponsor',
            },
        ),
        migrations.CreateModel(
            name='SubmissionForm',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('required_docs', models.CharField(max_length=200)),
                ('steps_to_apply', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'submission_form',
            },
        ),
        migrations.CreateModel(
            name='Tenure',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('duration', models.DurationField()),
            ],
            options={
                'db_table': 'tenure',
            },
        ),
    ]
