# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-02 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='university',
        ),
        migrations.RemoveField(
            model_name='field',
            name='department',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='expertise',
        ),
        migrations.RemoveField(
            model_name='student',
            name='skills',
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(related_name='skills', to='main.Specialization'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Field',
        ),
    ]
