# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-23 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager
import main.managers


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180723_0754'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='professor',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('object', main.managers.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='student',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('object', main.managers.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('object', main.managers.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
