# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-02 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180802_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('full time', 'full time'), ('part time', 'part time')], max_length=50),
        ),
    ]
