# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-17 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_organization_professor_schedule_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPosition',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('experience_required', models.CharField(max_length=20)),
                ('deadline', models.DateTimeField()),
                ('source', models.TextField()),
                ('contacts', models.ManyToManyField(to='main.Contact')),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_duration', to='main.Tenure')),
                ('fee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission_fee', to='main.Fee')),
                ('information', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='about_job', to='main.About')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offered_job', to='main.Job')),
                ('job_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue', to='main.Location')),
                ('job_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Professor')),
                ('requirements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='main.Qualifications')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income', to='main.Salary')),
                ('skills_covered', models.ManyToManyField(to='main.Specialization')),
                ('submission_form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application_form', to='main.SubmissionForm')),
            ],
        ),
    ]
