# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-02 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180802_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('X', 'X')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentposition',
            name='experience_required',
            field=models.CharField(choices=[('0-1 Years', '0-1 Years'), ('2-3 Years', '2-3 Years'), ('4-5 Years', '4-5 Years'), ('5+ Years', '5+ Years')], max_length=20),
        ),
    ]
