# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-17 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_studentposition'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentposition',
            table='student_job_position',
        ),
    ]
