# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-17 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180717_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('funding', models.FloatField(blank=True, null=True)),
                ('number_of_positions', models.IntegerField(default=0)),
                ('deadline', models.DateTimeField()),
                ('scholarship_maintenance_criteria', models.CharField(blank=True, max_length=100, null=True)),
                ('perks_offered', models.CharField(max_length=150)),
                ('source', models.TextField()),
                ('amount_granted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grant', to='main.Grant')),
                ('application_form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission_form', to='main.SubmissionForm')),
                ('contacts', models.ManyToManyField(related_name='contact_information', to='main.Contact')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='main.Qualifications')),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_duration', to='main.Tenure')),
                ('fields_of_interest', models.ManyToManyField(related_name='competencies', to='main.Specialization')),
                ('host_universities', models.ManyToManyField(related_name='host_regions', to='main.Location')),
                ('information', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='about_scholarship', to='main.About')),
                ('sponsors', models.ManyToManyField(related_name='funders', to='main.Sponsor')),
            ],
            options={
                'db_table': 'scholarship',
            },
        ),
    ]
