# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-15 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180803_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenure',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.CharField(max_length=30, validators=[main.validators.check_currency_format]),
        ),
        migrations.AlterField(
            model_name='fee',
            name='amount',
            field=models.CharField(max_length=30, validators=[main.validators.check_currency_format]),
        ),
        migrations.AlterField(
            model_name='grant',
            name='amount',
            field=models.CharField(max_length=30, validators=[main.validators.check_currency_format]),
        ),
        migrations.AlterField(
            model_name='salary',
            name='amount',
            field=models.CharField(max_length=30, validators=[main.validators.check_currency_format]),
        ),
    ]
