# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-17 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_scholarship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('call_for_paper_deadline', models.DateTimeField()),
                ('key_speakers', models.TextField(blank=True, null=True)),
                ('source', models.TextField()),
                ('ranking', models.CharField(blank=True, max_length=10, null=True)),
                ('conference_venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Location')),
                ('contacts', models.ManyToManyField(to='main.Contact')),
                ('covered_expenses', models.ManyToManyField(related_name='covered_expenses', to='main.Expense')),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_duration', to='main.Tenure')),
                ('fields_of_interest', models.ManyToManyField(related_name='interests', to='main.Specialization')),
                ('info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conference_information', to='main.About')),
                ('sponsors', models.ManyToManyField(related_name='organizers', to='main.Sponsor')),
            ],
            options={
                'db_table': 'conference',
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='related_conference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_conferences', to='main.Conference'),
        ),
    ]
