# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-16 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180815_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='numeric_value',
            field=models.FloatField(default=0),
        ),
    ]
