# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-18 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180717_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='studentposition',
            name='information',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
