# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-16 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_grant_numeric_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='numeric_value',
            field=models.FloatField(default=0),
        ),
    ]
